# Generated by Django 5.2 on 2025-04-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aquisicao', models.DateField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('emprestado', 'Emprestado'), ('baixado', 'Baixado')], default='disponivel', max_length=20)),
            ],
        ),
    ]
